### ISSUE TITLE
"Command exception Pause.getAllFrames SecurityError: Blocked a frame with origin"

### ISSUE THREAD

**Issue by loganfsmyth** [replayio/chromium#18]
Seeing this in the logs for recording 63960e1f-6cf8-4e1d-9d7e-80ad227be54d
```
[18:53:28.908Z] error UnhandledError {"controlId":"5e5fb0b6-444a-4268-8772-b1ea45909c43","processId":17,"threadId":1,"linkerTime":55.307,"line":"Error: Command exception Pause.getAllFrames SecurityError: Blocked a frame with origin \"https://tag.idsync.analytics.yahoo.com\" from accessing a cross-origin frame."}
```
Sounds like something in there needs a try-catch, or that our JS code isn't running with enough permissions to access everything on the page.

**Comment by bhackett1024** [comment]
Hmm, Pause.getAllFrames needs to return a complete stack for the point it's at --- all frames for scripts which we instrument (all content scripts, but not browser internal scripts) need to be included.  From the exception here it's not clear whether the frame hitting the permissions issue is an instrumented script; improving the error message to include the other origin would be good to understand the problem here better.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-147](https://linear.app/replay/issue/RUN-147/command-exception-pausegetallframes-securityerror-blocked-a-frame-with)
